#!/usr/bin/env bash
#This script displays the string 'Best School' ten times and in the nine line displays a 'Hi'.
i=0
while [ $i -lt 10 ]
do
     echo "Best School"
	(( i++ ))
     if [ $i == 9 ]
	then
	    echo "Hi"
     else
	 true
        fi
	
done	
