#!/usr/bin/env bash
#This scripts displays 'Best School' but in the line 4th displays 'bad luck' and in the line 8th displays good luck.
i=0
while [ $i -lt 8 ]
do
	echo "Best School"
	(( i++ ))
	if [ $i == 3 ]
	then
		echo "bad luck"
	elif [ $i == 7 ]
	then
		echo "good luck"
	else
		true
	fi
done
