#!/usr/bin/env bash
#This scripts displays numbers from 1 to 20 but after the line 4, it displays the string 'bad luck from China', after the line 9, it displays 'bad luck from Japan' and after the line 17, it displays the string 'bad luck from Italy'.
i=1
while [ $i -le 20 ]
do
    echo $i   
    (( i++ ))
    
    case "$i" in
	"5") echo "bad luck from China"
	 ;;
        "10") echo "bad luck from Japan"
	 ;;     
	"18") echo "bad luck from Italy"
	 ;;     
    esac
done
