#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes. The hours fro 0 to 12 and the minutes from 1 to 59.
h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    (( h++ ))
    
    case $h in
	1|2|3|4|5|6|7|8|9|10|11|12|13) echo {1..59} | tr ' ' '\n'
	;;
    esac 
done	
