#!/usr/bin/env bash
#This script displays the content of the current directory in list format.

for x in $(find . -type f | cut -f 2- -d '-'  | cut -d'.' -f  1- | cut -d'/' -f  1- )
do
    echo "$x"
    
done
