#!/usr/bin/env bash
#This script displays information about the School file with conditions.
if [ -e "school" ]
 then
     echo "school file exists"

     if [ -s "school" ]
     then
	 echo "school file is not empty"
     else
	 echo "school file is empty"
     fi
     if [ -f "school" ]
	then
            echo "school is a regular file"
     else
	 true
	 fi
    
 else
        echo "school file does not exist" 
 fi	
