#!/usr/bin/env bash
#This script displays information about the School file with conditions.
fe=(-f "school")
if [ $fe ]
 then
     echo "school file exists"
     if [ $fe -empty ]
     then
	 echo "school file is empty"
     else
	 echo "school file is not empty"
     fi
     if [ $fe - ]
     then
	 echo "school is a regular file"
     else
	 true
     fi
     
 else
        echo "school file does not exist" 
 fi	
