#!/usr/bin/env bash
#This script displays information about the School file with conditions.
if [ -f "school" ]
 then
     echo "school file exists"

     if [ -s "school" ]
     then
	 echo "school file is empty"
     else
	 echo "school file is not empty"
     fi
         echo "school is a regular file"
    
     
 else
        echo "school file does not exist" 
 fi	
