#!/usr/bin/env bash
#Manage my process
argv1=$1
start()
{
./manage_my_process & echo $! > "/var/run/my_process.pid" && echo "manage_my_process started"
}
stop() {
sudo pkill -f "./manage_my_process" && sudo rm "/var/run/my_process.pid" && echo "manage_my_process stopped"
}
restart() {
sudo pkill -f "./manage_my_process"
sudo rm  "var/run/my_process.pid"
./manage_my_process & echo $! > "/var/run/my_process.pid"
echo manage_my_process restarted
}
case "$argv1" in
start) start
;;
stop)  stop
;;
restart) restart
;;
*) echo "Usage: manage_my_process {start|stop|restart}"
;;
esac
